window.mockProperties = [
  {
    id: 1,
    title: "Sea-facing Luxury Villa",
    location: "Rushikonda, Visakhapatnam",
    price: 150000000,
    bedrooms: 5,
    bathrooms: 6,
    area: 7500,
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Villa",
    status: "Sale",
    description: "A stunning modern glass villa with panoramic views of the Bay of Bengal, featuring an infinity pool, smart home technology, and exquisite finishes throughout."
  },
  {
    id: 2,
    title: "MVP Premium Apartment",
    location: "MVP Colony, Visakhapatnam",
    price: 45000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    image: "https://images.unsplash.com/photo-1502672260266-1c1e5250bc69?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Apartment",
    status: "Rent",
    description: "Spacious family apartment located in the heart of MVP Colony. Close to schools, shopping, and only 10 minutes from the beach."
  },
  {
    id: 3,
    title: "IT SEZ Executive House",
    location: "Madhurawada, Visakhapatnam",
    price: 65000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    image: "https://images.unsplash.com/photo-1583608205712-bea7210e75a1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "House",
    status: "Rent",
    description: "Perfect home for IT professionals working in Madhurawada SEZ. Features a large garden, modern kitchen, and quiet neighborhood."
  },
  {
    id: 4,
    title: "Beach Road Penthouse",
    location: "Beach Road, Visakhapatnam",
    price: 85000000,
    bedrooms: 4,
    bathrooms: 4,
    area: 4000,
    image: "https://images.unsplash.com/photo-1512918580421-df56bbdf3d98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Penthouse",
    status: "Sale",
    description: "Exclusive top-floor living with unobstructed views of the RK Beach. Includes a private terrace, jacuzzi, and premium Italian marble floors."
  },
  {
    id: 5,
    title: "Bheemili Coastal Estate",
    location: "Bheemili, Visakhapatnam",
    price: 220000000,
    bedrooms: 6,
    bathrooms: 7,
    area: 12000,
    image: "https://images.unsplash.com/photo-1576941089067-2de309012474?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Estate",
    status: "Sale",
    description: "Expansive heritage-style estate located near Bheemunipatnam. Comes with private beach access, a huge lawn, and colonial architecture."
  },
  {
    id: 6,
    title: "Bandra Sea Link Penthouse",
    location: "Bandra West, Mumbai",
    price: 450000000,
    bedrooms: 4,
    bathrooms: 4.5,
    area: 4200,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Penthouse",
    status: "Sale",
    description: "Exclusive penthouse living with floor-to-ceiling windows overlooking the Arabian Sea. Includes private elevator access and a sprawling rooftop terrace."
  },
  {
    id: 7,
    title: "Juhu Beach Villa",
    location: "Juhu, Mumbai",
    price: 850000000,
    bedrooms: 6,
    bathrooms: 7,
    area: 8500,
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Villa",
    status: "Sale",
    description: "A spectacular ultra-luxury villa right on Juhu beach, favored by celebrities. Includes home theater, private gym, and high-tech security."
  },
  {
    id: 8,
    title: "Powai Lakeview Apartment",
    location: "Powai, Mumbai",
    price: 120000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1900,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Apartment",
    status: "Rent",
    description: "Beautifully furnished apartment offering scenic views of Powai Lake. Located in a premium gated community with full amenities."
  },
  {
    id: 9,
    title: "South Bombay Heritage House",
    location: "Colaba, Mumbai",
    price: 350000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3000,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "House",
    status: "Rent",
    description: "Exquisite heritage townhome located in the quiet lanes of Colaba. Retains vintage charm with modern upgraded facilities."
  },
  {
    id: 10,
    title: "Worli High-Rise Condo",
    location: "Worli, Mumbai",
    price: 320000000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    image: "https://images.unsplash.com/photo-1449844908441-8829872d2607?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Apartment",
    status: "Sale",
    description: "Sky-high luxury living with breathtaking views of the Mumbai skyline and sea link. Features access to a private club and concierge."
  },
  {
    id: 11,
    title: "Tech Park Independent House",
    location: "Whitefield, Bangalore",
    price: 120000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "House",
    status: "Rent",
    description: "Beautiful independent family home available for rent in a premium gated community featuring a large backyard and proximity to top tech parks."
  },
  {
    id: 12,
    title: "Indiranagar Luxury Villa",
    location: "Indiranagar, Bangalore",
    price: 180000000,
    bedrooms: 5,
    bathrooms: 5,
    area: 5500,
    image: "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Villa",
    status: "Sale",
    description: "Contemporary luxury in Bangalore's most vibrant neighborhood. Featuring a zen garden, private pool, and open concept design."
  },
  {
    id: 13,
    title: "Koramangala Premium Penthouse",
    location: "Koramangala, Bangalore",
    price: 95000000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Penthouse",
    status: "Sale",
    description: "Opulent penthouse in a highly sought-after area, boasting huge wrap-around balconies and state-of-the-art home automation."
  },
  {
    id: 14,
    title: "Hebbal Lakeside Estate",
    location: "Hebbal, Bangalore",
    price: 250000000,
    bedrooms: 6,
    bathrooms: 6,
    area: 8000,
    image: "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Estate",
    status: "Sale",
    description: "A private oasis overlooking Hebbal lake. Comes with incredible outdoor entertainment areas, a guest house, and lush landscaping."
  },
  {
    id: 15,
    title: "Electronic City Studio",
    location: "Electronic City, Bangalore",
    price: 35000,
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    image: "https://images.unsplash.com/photo-1542314831-c6a4d14effbab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Apartment",
    status: "Rent",
    description: "Perfectly designed smart studio apartment for professionals, featuring modular furniture and access to coworking spaces in the building."
  },
  {
    id: 16,
    title: "Banjara Hills Premium Apartment",
    location: "Banjara Hills, Hyderabad",
    price: 65000000,
    bedrooms: 3,
    bathrooms: 3.5,
    area: 2400,
    image: "https://images.unsplash.com/photo-1502672260266-1c1e5250bc69?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Apartment",
    status: "Sale",
    description: "Ultra-luxurious Vastu-compliant apartment with premium Italian marble flooring, high ceilings, and a massive balcony."
  },
  {
    id: 17,
    title: "Jubilee Hills Grand Villa",
    location: "Jubilee Hills, Hyderabad",
    price: 350000000,
    bedrooms: 6,
    bathrooms: 7,
    area: 9000,
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Villa",
    status: "Sale",
    description: "Magnificent palatial villa offering unmatched luxury. Features a private cinema, massive swimming pool, and quarters for staff."
  },
  {
    id: 18,
    title: "HITEC City Tech Penthouse",
    location: "HITEC City, Hyderabad",
    price: 180000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3600,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Penthouse",
    status: "Rent",
    description: "Live above the clouds in the IT hub. Fully furnished with ultra-modern decor, perfect for expat executives."
  },
  {
    id: 19,
    title: "Gachibowli Family House",
    location: "Gachibowli, Hyderabad",
    price: 85000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "House",
    status: "Rent",
    description: "Quiet and secure independent house ideal for families, located within a short drive to major international schools and corporate offices."
  },
  {
    id: 20,
    title: "Manikonda Modern Estate",
    location: "Manikonda, Hyderabad",
    price: 140000000,
    bedrooms: 5,
    bathrooms: 5,
    area: 6500,
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Estate",
    status: "Sale",
    description: "A newly built estate blending modern architecture with lush green surroundings. Excellent connectivity to the financial district."
  },
  {
    id: 21,
    title: "Heritage Bungalow (For Rent)",
    location: "South Extension, New Delhi",
    price: 250000,
    bedrooms: 6,
    bathrooms: 7,
    area: 9500,
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "House",
    status: "Rent",
    description: "A regal heritage bungalow available for long-term lease. Features lush green lawns, colonial architecture, and modern opulent interiors."
  },
  {
    id: 22,
    title: "Vasant Vihar Elite Villa",
    location: "Vasant Vihar, New Delhi",
    price: 420000000,
    bedrooms: 5,
    bathrooms: 6,
    area: 8000,
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Villa",
    status: "Sale",
    description: "Situated in Delhi's most prestigious diplomatic enclave, this villa offers unparalleled privacy, grand entertaining spaces, and bespoke finishes."
  },
  {
    id: 23,
    title: "Gurgaon Golf Course Penthouse",
    location: "Golf Course Road, Gurgaon",
    price: 280000000,
    bedrooms: 4,
    bathrooms: 5,
    area: 5200,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Penthouse",
    status: "Sale",
    description: "Breathtaking golf course views from this super-luxury penthouse. Includes access to a world-class clubhouse and 5-star amenities."
  },
  {
    id: 24,
    title: "Noida Expressway Apartment",
    location: "Sector 150, Noida",
    price: 45000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Apartment",
    status: "Rent",
    description: "Bright and airy high-rise apartment in a sports city development, offering huge green spaces and excellent sports facilities."
  },
  {
    id: 25,
    title: "Chhatarpur Farm House",
    location: "Chhatarpur, New Delhi",
    price: 550000000,
    bedrooms: 7,
    bathrooms: 8,
    area: 25000,
    image: "https://images.unsplash.com/photo-1576941089067-2de309012474?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Estate",
    status: "Sale",
    description: "An awe-inspiring massive farmhouse estate spread over 2.5 acres. Includes a swimming pool, tennis court, and extensive landscaped gardens."
  },
  {
    id: 26,
    title: "Beachfront Goan Estate",
    location: "Assagao, Goa",
    price: 180000000,
    bedrooms: 5,
    bathrooms: 6,
    area: 6000,
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Estate",
    status: "Sale",
    description: "Private Portuguese-style estate offering direct beach access, a private pool, lush tropical gardens, and a dedicated entertainment villa."
  },
  {
    id: 27,
    title: "Anjuna Party Villa",
    location: "Anjuna, Goa",
    price: 350000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Villa",
    status: "Rent",
    description: "The ultimate vacation rental in Goa. Fully serviced luxury villa with an outdoor bar, pool, and walking distance to iconic cafes."
  },
  {
    id: 28,
    title: "ECR Sea View House",
    location: "ECR, Chennai",
    price: 120000000,
    bedrooms: 4,
    bathrooms: 4,
    area: 4500,
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "House",
    status: "Sale",
    description: "Stunning independent house located on the scenic East Coast Road. Features private beach access and gorgeous sunrises over the Bay of Bengal."
  },
  {
    id: 29,
    title: "Adyar River View Apartment",
    location: "Adyar, Chennai",
    price: 75000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    image: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    type: "Apartment",
    status: "Rent",
    description: "Breezy and bright apartment overlooking the Adyar estuary. Located in a prime, peaceful residential neighborhood."
  },
  {
    id: 30,
    title: "Pune Koregaon Park Penthouse",
    location: "Koregaon Park, Pune",
    price: 110000000,
    bedrooms: 4,
    bathrooms: 4,
    area: 4000,
    image: "https://images.unsplash.com/photo-1449844908441-8829872d2607?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    type: "Penthouse",
    status: "Sale",
    description: "Luxurious top-floor living in Pune's most elite area. Surrounded by ancient banyan trees, hip cafes, and premium boutiques."
  }
];
